id: aea44bf349ca471e8e3ca11d91e9eb43
initial_creation_type: ocr
source_metadata:
  volumes:
    2cb393e40b60499cb82cc79af4f39bdb:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མའི་དཀའ་འགྲེལ།
      total_pages: 1902
      volume_number: 64
